In [1]:
import numpy as np
rr=np.random.rand(1,2)
print(rr)
rr.shape
type(rr)

[[0.87777003 0.12553653]]


numpy.ndarray

# Introduction to Deep Learning with PyTorch
## TD1: Intro to Pytorch and tensors 

In this notebook, you'll get introduced to [PyTorch](http://pytorch.org/), a framework for building and training neural networks. PyTorch in a lot of ways behaves like the arrays from Numpy.  PyTorch takes these tensors and makes it simple to move them to GPUs for the faster processing needed when training neural networks. It also provides a module that automatically calculates gradients (for backpropagation!) and another module specifically for building neural networks. 



## Neural Networks

 
<img src="Td_images/simple_neuron.png" width=400px>



$$
\begin{align}
y &= f(w_1 x_1 + w_2 x_2 + b) \\
y &= f\left(\sum_i w_i x_i +b \right)
\end{align}
$$

With vectors this is the dot/inner product of two vectors:

$$
h = \begin{bmatrix}
x_1 \, x_2 \cdots  x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_1 \\
           w_2 \\
           \vdots \\
           w_n
\end{bmatrix}
$$

## Tensors

 A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). The fundamental data structure for neural networks are tensors and PyTorch is built around tensors.

<img src="TD_images/tensor_examples.svg" width=600px>

With the basics covered, it's time to explore how we can use PyTorch to build a simple neural network.

In [3]:
# First, import PyTorch
import torch


i imported torch


In [4]:
#trying basic commandes
# you first command


3


this is my text, i cna writw here whatever i want
lets amke a heading 
# heading 

In [4]:
import torch

In [5]:
def activation(x):
    sig=1/(1+torch.exp(-x))
    sig=1/(1+torch.exp(-x))

    return sig
#what does return do? 

In [5]:
### Generate some data
torch.manual_seed(7)# Set the random seed so things are predictable 
#setting same seed leads to reproducibility 
#Example:  what if you initilize randomly ? 

# Features are 5 random normal variables
features = 

# True weights for our data, random normal variables again
weights = 

# and a true bias term
bias = 

features are: tensor([[ 0.4219, -1.2384, -0.4437, -0.4012, -0.0838]])
weights are: tensor([[-0.9816,  0.0870,  0.5195,  1.0693, -0.9893]])
bias is :  tensor([[-0.8282]])


torch.Tensor

In [6]:
print(features)
print(features.shape)
type(features)


tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
torch.Size([1, 5])


torch.Tensor

Purpose: Illustration. 
Above data generated, we can use to get the output of our simple network
It is random for now.  

Explanation for each line:  

`features = torch.randn((1, 5))` creates a tensor with shape `(1, 5)`, one row and five columns, that contains values randomly distributed according to the normal distribution with a mean of zero and standard deviation of one. 

`weights = torch.randn_like(features)` creates another tensor with the same shape as `features`, again containing values from a normal distribution.

Finally, `bias = torch.randn((1, 1))` creates a single value from a normal distribution.

Note : PyTorch tensors can be added, multiplied, subtracted, etc, just like Numpy arrays.

In general, you'll use PyTorch tensors pretty much the same way you'd use Numpy arrays. 

They come with some nice benefits though such as GPU acceleration which we'll get to later. 

For now, let us use the generated data to calculate the output of this simple single layer network. 


In [7]:
#print feautes, bias, weights....
print(features)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])


In [8]:
# what kind of object is bias? 
print(bias)
type(bias)


tensor([[0.3177]])


torch.Tensor

In [10]:
print(features.sum())

tensor(2.1626)


In [25]:
#now, all operation of matrix (numpy) can be performed on this torch variable. 
print(features.sum())
#print(bias.abs()) #press tab to show more options. 
#refer to help link on torch variables.

tensor(2.1626)


 **Exercise**: Calculate the output of the network with input features `features`, weights `weights`, and bias `bias`. Similar to Numpy, PyTorch has a [`torch.sum()`](https://pytorch.org/docs/stable/torch.html#torch.sum) function, as well as a `.sum()` method on tensors, for taking sums. Use the function `activation` defined above as the activation function.

In [14]:
## Calculate the output of this network using the weights and bias tensors
###  Your Solution
x=
y1=
print(y1)

#two ways to do thae same
y1 = activation(torch.sum(features * weights) + bias)
y2 = activation((features * weights).sum() + bias)
# Now, make our labels from our data and true weights



NameError: name 'activation' is not defined

In [29]:
print(y1)
print(y2)

tensor([[0.1595]])
tensor([[0.1595]])


You can do the multiplication and sum in the same operation using a matrix multiplication. 
Use matrix multiplications since they are 
more efficient and accelerated using 
modern libraries and high-performance computing on GPUs.

Here, we want to do a matrix multiplication of the features and the weights. For this we can use [`torch.mm()`](https://pytorch.org/docs/stable/torch.html#torch.mm)
or [`torch.matmul()`](https://pytorch.org/docs/stable/torch.html#torch.matmul) which is somewhat more complicated and supports broadcasting. 
If we try to do it with `features` and `weights` as they are, we'll get an error

```python
>> torch.mm(features, weights)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-15d592eb5279> in <module>()
----> 1 torch.mm(features, weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1524590658547/work/aten/src/TH/generic/THTensorMath.c:2033
```

Why the error?? 
Answer: Our tensors aren't the correct shapes to perform a matrix multiplication. 
Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second column. 
Note: Both `features` and `weights` have the same shape, `(1, 5)`.

Thus, we need to change the shape of `weights` to get the matrix multiplication to work.

**Note:** To see the shape of a tensor called `tensor`, use `tensor.shape`. If you're building neural networks, you'll be using this method often.

There are a few options here: [`weights.reshape()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.reshape), [`weights.resize_()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_), and [`weights.view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view).

* `weights.reshape(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)` sometimes, and sometimes a clone, as in it copies the data to another part of memory.
* `weights.resize_(a, b)` returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory). If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory. Here I should note that the underscore at the end of the method denotes that this method is performed **in-place**. Here is a great forum thread to [read more about in-place operations](https://discuss.pytorch.org/t/what-is-in-place-operation/16244) in PyTorch.

**Important** 

* `weights.view(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)`.

**Preferebly  use `.view()`,** but any of the three methods will work for this.
So, now we can reshape `weights` to have five rows and one column with something like `weights.view(5, 1)`.

> **Exercise**: Calculate the output of our little network using matrix multiplication.

In [12]:
print(weights)
print(weights.view(5,1))

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])


In [17]:
## Calculate the output of this network using matrix multiplication

y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


### Stack them up!

That's how you can calculate the output for a single neuron. The real power of this algorithm happens when you start stacking these individual units into layers and stacks of layers, into a network of neurons. The output of one layer of neurons becomes the input for the next layer. With multiple input units and output units, we now need to express the weights as a matrix.

<img src='TD_images/multilayer_diagram_weights.png' width=450px>

The first layer shown on the bottom here are the inputs, understandably called the **input layer**. The middle layer is called the **hidden layer**, and the final layer (on the right) is the **output layer**. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [19]:
### Generate some data
 # Set the random seed so things are predictable

# Features are 3 random normal variables
features =

# Define the size of each layer in our network
n_input =    # Number of input units, must match number of input features
n_hidden =                    # Number of hidden units 
n_output =                     # Number of output units

# Weights for inputs to hidden layer
W1 = # [2X]
# Weights for hidden layer to output layer
W2 = 

# and bias terms for hidden and output layers
B1 = 
B2 = 

> **Exercise:** Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`. 

In [20]:
## propose a solution
z=
h=
output=
print(output)


tensor([[0.3171]])




If you did this correctly, you should see the output `tensor([[ 0.3171]])`.

The number of hidden units a parameter of the network, often called a **hyperparameter** to differentiate it from the weights and biases parameters.

## Numpy to Torch and back

PyTorch has a great feature for converting between Numpy arrays and Torch tensors. 
To create a tensor from a Numpy array, use `torch.from_numpy()`. 
To convert a tensor to a Numpy array, use the `.numpy()` method.

In [ ]:
#solution to previous :


In [ ]:
import numpy as np
a = np.random.rand(4,3)
a

In [ ]:
b = torch.from_numpy(a)
b

In [ ]:
b.numpy()

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [ ]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

In [ ]:
# Numpy array matches new values from Tensor
a